"""Tab. mixing-decode (figs/mixing_decode.tex): one pair decoded along the edge.

The former colorband panel of Fig. 2, as a table: for the pair in the colorband
cache (pairCSML_00), one cell per method and per ideal mixing weight (25 / 50 /
75 % on paper B). A cell holds the opening of the ACTUAL decoded abstract (whole
sentences up to a word budget, then an ellipsis) and nothing else: the measured
landing position on the A->B axis, which the colorband cells were coloured by,
is carried by Fig. 2e and is not repeated per cell here. The tabular only; the
caption (with the two papers' titles) lives in the manuscript.

Terms that belong to paper A (statistical mechanics of learning) are set in
blue and terms of paper B (quantum error-correcting codes) in orange, so the
reader sees which source a cell draws on (#167 R5). The tabular is drawn wider
than the text block and scaled down with \resizebox, which fits longer openings.

Dual mode: driven by Snakemake (workflow/rules/fig2_pacs_clustering.smk) or

    python workflow/scripts/fig2_mixing_table.py \
        --band    data/pair_axis/results/colorband_pairCSML_00_pairaxis.json \
        --decodes data/pair_axis/results/absfollow_pairCSML_00_pairaxis.json \
        --icae    data/pair_axis/results/absfollow_pairCSML_00_pairaxis_icae.json \
        --out     figs/mixing_decode.tex
"""
import argparse
import json
import os
import re
import sys

METHODS = [("doc2lora", r"\doctolora"), ("icae", r"\texttt{ICAE}"), ("incontext", "in-context")]
FRACS = [0.25, 0.5, 0.75]
MIN_WORDS, MAX_WORDS = 30, 42     # keep whole sentences past MIN_WORDS; hard cut at MAX_WORDS

# source terms, longest first so "statistical mechanics of learning" wins over its prefix;
# colours are the Fig. 2 palette's blue / orange (workflow/plot/_fig2_palette.py)
TERMS = {
    "paperA": [r"statistical[- ]mechanic(?:s|al)(?: of learning(?: from examples)?)?",
               r"(?:feedforward )?neural networks?", r"generali[sz]ation (?:error|performance)",
               r"learning curves?", r"replica(?:-based)?(?: method)?", r"perceptrons?",
               r"Gibbs", r"spin-glass", r"training (?:set|samples|data)"],
    "paperB": [r"quantum error[- ]correct(?:ing|ion)(?: codes?)?", r"QECCs?", r"QEC",
               r"error-correcting codes?", r"qubits?", r"quantum computing",
               r"quantum information", r"decoherence", r"quantum noise"],
}
COLORS = {"paperA": "2A78D6", "paperB": "EB6834"}

_TEX = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def tex_escape(s):
    s = "".join(_TEX.get(c, c) for c in s)
    return s.replace("...", r"\ldots{}").replace("“", "``").replace("”", "''")


def opening(text, min_words=MIN_WORDS, max_words=MAX_WORDS):
    """The first sentences of `text` up to a word budget, ending in an ellipsis if cut."""
    text = " ".join((text or "").split())
    sents = re.split(r"(?<=[.!?])\s+", text)
    out, n = [], 0
    for s in sents:
        out.append(s)
        n += len(s.split())
        if n >= min_words:
            break
    words = " ".join(out).split()
    if len(words) > max_words:
        return " ".join(words[:max_words]).rstrip(",;:.") + "…"
    if n < len(text.split()):
        return " ".join(words).rstrip(".") + "…"
    return " ".join(words)


def highlight(tex):
    """Colour the source terms of paper A and paper B in an escaped cell."""
    alts = [(t, c) for c, ts in TERMS.items() for t in ts]
    rx = re.compile("|".join(f"(?P<g{i}>{t})" for i, (t, _) in enumerate(alts)), re.I)
    return rx.sub(lambda m: rf"\textcolor{{{alts[int(m.lastgroup[1:])][1]}}}{{{m.group(0)}}}", tex)


def _fmt(x):
    s = f"{x:.2f}"
    return s[1:] if s.startswith("0") else s


def load_cells(base_path, icae_path):
    cells = {}
    for path, keep in [(base_path, ("doc2lora", "incontext")), (icae_path, ("icae",))]:
        if not path or not os.path.exists(path):
            continue
        for c in json.load(open(path))["cells"]:
            cells.setdefault(tuple(c["bary"]), {}).update({k: v for k, v in c.items() if k in keep})
    return cells


def main(band, decodes, icae, out):
    D = json.load(open(band))
    R = D["grid_den"]
    cells = load_cells(decodes, icae)
    cA, cB = D["corners"]["A"], D["corners"]["B"]

    lines = [
        "% Generated by workflow/scripts/fig2_mixing_table.py (snakemake fig2); do not edit by hand.",
        f"% Pair {D['set']}: A = {cA['name']} ({cA.get('doi')}); B = {cB['name']} ({cB.get('doi')}).",
        f"% Cells: opening of the decoded abstract (whole sentences past {MIN_WORDS} words, cut at {MAX_WORDS});",
        "% paper-A terms blue, paper-B terms orange.",
        *(rf"\providecolor{{{c}}}{{HTML}}{{{h}}}" for c, h in COLORS.items()),
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{@{}l *{3}{>{\raggedright\arraybackslash}p{0.36\linewidth}}@{}}",
        r"\toprule",
        r"& \multicolumn{3}{c}{Ideal mixing weight on paper B} \\",
        r"\cmidrule(lr){2-4}",
        "Method & " + " & ".join(f"${int(f * 100)}\\,\\%$" for f in FRACS) + r" \\",
        r"\midrule",
    ]
    for key, name in METHODS:
        row = []
        for f in FRACS:
            k = round(f * R)
            rec = cells.get((R - k, k, 0), {}).get(key) or {}
            text = opening(rec.get("abs", ""))
            row.append(highlight(tex_escape(text)).replace("…", r"\ldots{}"))
        lines.append(name + " & " + " & ".join(row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}", ""]
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w") as fh:
        fh.write("\n".join(lines))
    print("wrote", out)


if "snakemake" in sys.modules:
    main(snakemake.input["band_json"], snakemake.input["decodes"], snakemake.input["icae"],
         snakemake.output["tex"])
elif __name__ == "__main__":
    SKG = "data/pair_axis"
    ap = argparse.ArgumentParser()
    ap.add_argument("--band", default=f"{SKG}/results/colorband_pairCSML_00_pairaxis.json")
    ap.add_argument("--decodes", default=f"{SKG}/results/absfollow_pairCSML_00_pairaxis.json")
    ap.add_argument("--icae", default=f"{SKG}/results/absfollow_pairCSML_00_pairaxis_icae.json")
    ap.add_argument("--out", default="figs/mixing_decode.tex")
    a = ap.parse_args()
    main(a.band, a.decodes, a.icae, a.out)
