# PACS-node label comparison (Doc2LoRA full-rank / vec2text / KeyLLM) + SI tables.
#
# FULL-RANK chain (replaces the old rank-pooled `decode_nodes_pooled.py` path,
# which was removed):
#   prep_nodes ───────────────> nodes.json            (SBERT centroid-nearest members per node)
#   compute_qwen_fullrank_means ─> qwen_fullrank_means.npz   (true [L=36,r=8,512] mean per node, GPU)
#       └─ decode_fullrank_field23 ─> qwen_fullrank_field23.json  (Doc2LoRA field labels, GPU)
#   decode_vec2text_nodes ────> vec2text_labels.json   (GTR-inversion baseline, GPU)
#   keyllm_faithful ──────────> keyllm_faithful_labels.json (raw KeyBERT/KeyLLM keywords)
#   icae_raw_labels ──────────> icae_raw.json             (raw ICAE decode, from git history)
#   bertopic_labels ──────────> bertopic*_labels.json  (BERTopic manual-mode c-TF-IDF keywords)
#       └─ bertopic_report ───> BERTOPIC.md            (+ SBERT-cosine supplement, all methods)
#   make_pacs_label_tables ───> pacs_labels_{main,si}.tex  (doc2lora-vs-true-PACS SI tables)
#   label_eval_prep ──────────> label_eval_nodes.json   (every method's native output per node)
#       ├─ label_eval_metric1 ─> fuzzy overlap (deterministic; the reported metric)
#       ├─ label_eval_metric4 ─> pairwise vs the official label (judge panel; `label_eval`)
#       └─ make_hierarchy_rows > paper/iclr2026/hierarchy_rows.tex  (Tab. hierarchy-labels)
#
# Label tables in the paper:
#   - Tab. hierarchy-labels  -> paper/iclr2026/hierarchy_rows.tex  (GENERATED by
#                               bt_hierarchy_rows from label_eval_nodes.json)
#   - Tab. fields9-labels    -> typed inline in main.tex (no \input)
# The pacs_labels_*.tex SI tables are auto-generated here but not \input by the
# current draft. Assembling hierarchy_rows.tex / the fields9 rows in paper format
# is tracked separately (issue #15). bt_length_dial emits length_vs_breadth.csv (read
# by make_pacs_label_tables and Fig. cluster-labels) and the length-dial figure, which
# the current draft no longer includes.
#
# External deps: full-rank means/decode/vec2text need a GPU + qwen checkpoint
# (set baseline_trees_gpu in config); KeyLLM-from-keywords needs an ollama server
# (glm-5.1:cloud) on :11434; vec2text needs the `vec2text` package importable;
# BERTopic runs from its own .venv-bertopic (built by setup_bertopic_venv.sh).
from os.path import join as j

BT_DIR = "data/labels"
BT_CA_RESULTS = "data/pacs/results"
BT_FIGS_DIR = config.get("figs_dir", "figs")
BT_GPU = config.get("baseline_trees_gpu", "0")

# shared inputs (pre-existing source files; produced outside this workflow)
BT_PAPER_GROUPS = j(BT_CA_RESULTS, "paper_groups.parquet")
BT_GROUPS = j(BT_CA_RESULTS, "groups.parquet")
BT_PAPER_TEXT = j(APS_DIR, "paper_text.parquet")
BT_PAPER_TEXT_PID = j(APS_DIR, "paper_text_pid.parquet")
BT_SBERT = j(EMB_DIR, "sbert_allmpnet.npz")
BT_QWEN_NPZ = j(EMB_DIR, "qwen_norm_lora_emb.npz")   # rank-pooled genes (from embed_aps_papers_qwen)

# label/data outputs
BT_NODES = j(BT_DIR, "nodes.json")
BT_MEANS = j(BT_DIR, "qwen_fullrank_means.npz")
BT_FULLRANK = j(BT_DIR, "qwen_fullrank_field23.json")
BT_VEC2TEXT = j(BT_DIR, "vec2text_labels.json")
BT_KEYLLM = j(BT_DIR, "keyllm_faithful_labels.json")  # raw KeyBERT/KeyLLM keyword list
BT_ICAE = j(BT_DIR, "icae_raw.json")                 # raw ICAE decode (recovered from git history)
BT_INCONTEXT = j(BT_DIR, "incontext_labels.json")    # in-context text baseline (issue #29)

# BERTopic baseline: manual (predefined-cluster) topic modelling, so only its topic
# REPRESENTATION step is scored. Four arms: c-TF-IDF / KeyBERTInspired x top-10
# (BERTopic's default) / top-3 (a length-matched control for the metric's length
# penalty). The `_raw` run repeats the c-TF-IDF arms without stripping the LaTeX /
# MathML markup in APS abstracts, to separate method from preprocessing.
BT_BERTOPIC_VENV = ".venv-bertopic/.ready"
BT_BERTOPIC = [j(BT_DIR, f) for f in ("bertopic_labels.json", "bertopic3_labels.json",
                                      "bertopic_kbi_labels.json", "bertopic_kbi3_labels.json",
                                      "bertopic_topics.json")]
BT_BERTOPIC_RAW = [j(BT_DIR, f) for f in ("bertopic_raw_labels.json", "bertopic_raw3_labels.json",
                                          "bertopic_raw_kbi_labels.json",
                                          "bertopic_raw_kbi3_labels.json",
                                          "bertopic_raw_topics.json")]
BT_BERTOPIC_JUDGE = j(BT_DIR, "bertopic_judge.json")   # metric-4 panel, BERTopic in the field
BT_BERTOPIC_REPORT = j(BT_DIR, "bertopic_report.json")
BT_BERTOPIC_MD = j(BT_DIR, "BERTOPIC.md")

# Cluster-label evaluation (issue #24): aligned node table + two metrics.
BT_EVAL_NODES = j(BT_DIR, "label_eval_nodes.json")
BT_EVAL_M1 = j(BT_DIR, "label_eval_metric1.json")    # lexical overlap (no LLM)
BT_EVAL_M4 = j(BT_DIR, "label_eval_metric4.json")    # pairwise vs the official label (judge panel)
BT_EVAL_SUMMARY = j(BT_DIR, "label_eval_summary.json")   # reported report (M1 + length) (+ .md)

# Tab. hierarchy-labels, generated from the evaluation's own table so the
# qualitative table cannot drift from the scored strings (was hand-assembled, #15).
BT_HIER_ROWS = j(FIGS_DIR, "hierarchy_rows.tex")

# auto-generated SI tables (doc2lora label vs ground-truth PACS)
BT_PACS_MAIN = j(BT_DIR, "pacs_labels_main.tex")
BT_PACS_SI = j(BT_DIR, "pacs_labels_si.tex")

# length-dial figure (Fig. length-dial) + the centroid-norm-vs-scatter CSV it
# emits (also consumed by make_pacs_label_tables).
BT_RADIUS_CSV = j(BT_DIR, "length_vs_breadth.csv")
BT_LENGTH_DIAL = j(BT_FIGS_DIR, "length_dial.pdf")


# Code inputs of the rules that decode, extract, or call a model are ancient(): a fresh clone
# checks every script out newer than the archived outputs (the `results` tier), and an mtime
# trigger on the script would otherwise re-run a GPU job whose result already ships. After
# editing such a script, rerun its rule with -R <rule>. Table and figure rules keep plain
# script inputs.

rule bt_prep_nodes:
    input:
        paper_groups = BT_PAPER_GROUPS,
        groups = BT_GROUPS,
        paper_text = BT_PAPER_TEXT_PID,
        sbert = BT_SBERT,
        script = ancient(j(SCRIPTS, "prep_nodes.py")),
    output:
        nodes = BT_NODES,
    shell:
        "python {input.script}"


# Re-extract the FULL-RANK [L=36, r=8, 512] mean per node (the stored
# qwen_norm_lora_emb_raw.npz is rank-pooled, so full-rank structure is gone).
# Unsharded run (CAP=2000 members/node). For the full corpus, shard with
# `python compute_qwen_fullrank_means.py <CAP> <i/n>` then merge_fullrank_means.py.
rule bt_fullrank_means:
    input:
        paper_groups = BT_PAPER_GROUPS,
        paper_text = BT_PAPER_TEXT,
        ckpt = QWEN_CHECKPOINT_PATH,
        script = ancient(j(SCRIPTS, "compute_qwen_fullrank_means.py")),
    output:
        means = BT_MEANS,
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} python {input.script}"


# Decode the full-rank node means with the verbatim 2-3 word field prompt.
rule bt_decode_fullrank:
    input:
        means = BT_MEANS,
        ckpt = QWEN_CHECKPOINT_PATH,
        script = ancient(j(SCRIPTS, "decode_fullrank_field23.py")),
    output:
        labels = BT_FULLRANK,
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} python {input.script}"


# vec2text (GTR embedding inversion) baseline labels, same centroid-nearest
# retrieval as the other baselines.
rule bt_vec2text:
    input:
        paper_groups = BT_PAPER_GROUPS,
        paper_text = BT_PAPER_TEXT_PID,
        sbert = BT_SBERT,
        script = ancient(j(SCRIPTS, "decode_vec2text_nodes.py")),
    output:
        labels = BT_VEC2TEXT,
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} python {input.script}"


# Faithful KeyLLM keyword extraction: real KeyBERT/KeyLLM on each node's medoid
# document, minimax-m3 backend (issue #24). Native keyword-list output, no naming.
# Needs OPENROUTER_API_KEY + keybert.
rule bt_keyllm_faithful:
    input:
        nodes = BT_NODES,
        script = ancient(j(SCRIPTS, "keyllm_faithful.py")),
    output:
        keywords = j(BT_DIR, "keyllm_faithful_labels.json"),
    shell:
        "python {input.script}"


# Raw ICAE decoder output (icae_label.py answers the shared field prompt inside
# ICAE itself). The run predates the current tree, so this recovers the labels
# from the archived icae_tree.json in git history rather than re-running the
# checkpoint. CPU-only.
rule bt_icae_raw:
    input:
        script = ancient(j(SCRIPTS, "icae_raw_labels.py")),
    output:
        labels = BT_ICAE,
    shell:
        "python {input.script}"


rule bt_incontext:
    input:
        nodes = BT_NODES,
        script = ancient(j(SCRIPTS, "incontext_label_qwen.py")),
    output:
        labels = BT_INCONTEXT,
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} python {input.script}"


# Isolated venv for BERTopic (numpy 2 / umap / hdbscan stack; see the script).
rule bt_bertopic_venv:
    input:
        script = ancient("workflow/scripts/setup_bertopic_venv.sh"),
    output:
        ready = touch(BT_BERTOPIC_VENV),
    shell:
        "bash {input.script}"


# BERTopic keyword labels for the same PACS nodes every other method labels.
# One fit per hierarchy level over EVERY PACS group at that level with >= 100
# papers (9 / 65 / 393 groups), capped at 2000 members per node -- Doc2LoRA's CAP
# and seed. The GPU only speeds up KeyBERTInspired's word embedding.
rule bt_bertopic:
    input:
        nodes = BT_NODES,
        paper_groups = BT_PAPER_GROUPS,
        paper_text = BT_PAPER_TEXT,
        sbert = BT_SBERT,
        venv = BT_BERTOPIC_VENV,
        script = ancient(j(SCRIPTS, "bertopic_labels.py")),
    output:
        labels = BT_BERTOPIC,
    params:
        cap = config.get("bertopic_cap", 2000),
        min_docs = config.get("bertopic_min_docs", 100),
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} .venv-bertopic/bin/python {input.script} "
        "{params.cap} {params.min_docs} clean"


# Same run with the LaTeX / MathML markup left in: the preprocessing ablation.
rule bt_bertopic_raw:
    input:
        nodes = BT_NODES,
        paper_groups = BT_PAPER_GROUPS,
        paper_text = BT_PAPER_TEXT,
        sbert = BT_SBERT,
        venv = BT_BERTOPIC_VENV,
        script = ancient(j(SCRIPTS, "bertopic_labels.py")),
    output:
        labels = BT_BERTOPIC_RAW,
    params:
        cap = config.get("bertopic_cap", 2000),
        min_docs = config.get("bertopic_min_docs", 100),
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} .venv-bertopic/bin/python {input.script} "
        "{params.cap} {params.min_docs} raw"


# ── Cluster-label evaluation (issue #24) ──────────────────────────────────────
# Align every method's decoded label against the ground-truth PACS node, with a
# sampled ancestor/descendant for the altitude metric.
rule bt_label_eval_prep:
    input:
        nodes = BT_NODES,
        doc2lora = BT_FULLRANK,
        vec2text = BT_VEC2TEXT,
        keyllm = BT_KEYLLM,
        icae = BT_ICAE,
        incontext = BT_INCONTEXT,
        bertopic = BT_BERTOPIC,
        script = j(SCRIPTS, "label_eval_prep.py"),
    output:
        nodes_eval = BT_EVAL_NODES,
    shell:
        "python {input.script}"


# Metric 1 -- lexical overlap (token Jaccard + ROUGE-L) vs. the true PACS label.
# Cheap, no LLM.
rule bt_label_eval_metric1:
    input:
        nodes_eval = BT_EVAL_NODES,
        script = j(SCRIPTS, "label_eval_metric1.py"),
    output:
        metric1 = BT_EVAL_M1,
    shell:
        "python {input.script}"


rule bt_label_eval_metric4:
    input:
        nodes_eval = BT_EVAL_NODES,
        judges = j(SCRIPTS, "label_eval_judges.py"),
        script = j(SCRIPTS, "label_eval_metric4.py"),
    output:
        metric4 = BT_EVAL_M4,
    shell:
        "python {input.script}"


rule bt_label_eval_summary:
    input:
        metric1 = BT_EVAL_M1,
        nodes_eval = BT_EVAL_NODES,
        script = j(SCRIPTS, "label_eval_summary.py"),
    output:
        summary = BT_EVAL_SUMMARY,
        md = j(BT_DIR, "label_eval_summary.md"),
    shell:
        "python {input.script}"


# Aggregation: the cluster-label evaluation. Separate from `baseline_trees`
# because metric 4 hits the judge panel (OpenRouter + Vertex).
rule label_eval:
    input:
        BT_EVAL_M1,
        BT_EVAL_M4,
        BT_BERTOPIC_JUDGE,
        BT_EVAL_SUMMARY,


# Length-dial figure (Fig. length-dial): panel (a) computes centroid norm vs.
# cluster scatter live from the rank-pooled genes (emits length_vs_breadth.csv);
# panel (b) is a transcribed abstraction ladder. CPU-only. The script writes into
# BT_DIR, so copy the PDF into figs/ for the paper.
# The CSV is git-tracked (Fig. 2 panel (a) reads it), so the tracked script is
# ancient(): a fresh checkout must not make it look newer than the CSV and
# trigger a re-run over the full embedding table.
rule bt_length_dial:
    input:
        emb = BT_QWEN_NPZ,
        paper_groups = BT_PAPER_GROUPS,
        script = ancient(j(SCRIPTS, "make_length_dial.py")),
    output:
        csv = BT_RADIUS_CSV,
        fig = BT_LENGTH_DIAL,
    shell:
        "python {input.script} && cp {BT_DIR}/length_dial.pdf {output.fig}"


# Tab. hierarchy-labels: every method's native output per PACS node, taken from
# the evaluation's own aligned table so it shows exactly the strings that were
# scored. CPU-only. Writes straight into the manuscript directory.
rule bt_hierarchy_rows:
    input:
        nodes_eval = BT_EVAL_NODES,
        script = j(SCRIPTS, "make_hierarchy_rows.py"),
    output:
        rows = BT_HIER_ROWS,
    shell:
        "python {input.script} --out {output.rows}"


# Doc2LoRA label vs ground-truth PACS SI tables (main sample + full set).
# length_vs_breadth.csv comes from bt_length_dial.
rule bt_pacs_tables:
    input:
        labels = BT_FULLRANK,
        groups = BT_GROUPS,
        radius = BT_RADIUS_CSV,
        script = j(SCRIPTS, "make_pacs_label_tables.py"),
    output:
        main = BT_PACS_MAIN,
        si = BT_PACS_SI,
    shell:
        "python {input.script}"


# Metric 4's judge panel re-run with the BERTopic arms in the field. It imports
# the tournament from label_eval_metric4.py rather than forking it, and writes its
# OWN file: the win rate that metric reports is scored against the field, so adding
# arms would silently move every incumbent's number in the tracked
# label_eval_metric4.json that Fig. 2 (b) reads. The response cache is keyed on the
# labels, so only the BERTopic pairs cost anything (3,640 of 8,120 calls on the
# first run, nothing after). Needs OPENROUTER_API_KEY + Google ADC; sits behind the
# `label_eval` target with the other panel run, never on `paper_assets`.
# `DRY=1 python bertopic_judge.py` counts the uncached calls without spending.
# The Vertex seat also needs GOOGLE_CLOUD_PROJECT (or an ADC quota_project_id)
# naming a project with Vertex AI enabled -- see the script docstring; without it
# every gemini call spends ~23 s failing.
rule bt_bertopic_judge:
    input:
        nodes_eval = BT_EVAL_NODES,
        judges = j(SCRIPTS, "label_eval_judges.py"),
        tournament = j(SCRIPTS, "label_eval_metric4.py"),
        script = j(SCRIPTS, "bertopic_judge.py"),
    output:
        judged = BT_BERTOPIC_JUDGE,
    shell:
        "python {input.script}"


# BERTopic read-out: the lexical metric the evaluation reports is harsh on a
# keyword list, so this adds an SBERT-cosine supplement (scored identically for
# EVERY method, plus a shuffled-label chance level), a per-level split and a
# per-node head-to-head against Doc2LoRA. Uses the main env (sentence-transformers).
# It also folds in bertopic_judge.json when that file exists -- deliberately NOT a
# declared input, so `snakemake bertopic` stays LLM-free; run `snakemake
# label_eval` first (or bt_bertopic_judge) to get the judge tables in BERTOPIC.md.
rule bt_bertopic_report:
    input:
        nodes_eval = BT_EVAL_NODES,
        metric1 = BT_EVAL_M1,
        bertopic = BT_BERTOPIC,
        raw = BT_BERTOPIC_RAW,
        script = j(SCRIPTS, "bertopic_report.py"),
    output:
        report = BT_BERTOPIC_REPORT,
        md = BT_BERTOPIC_MD,
    resources:
        gpu = 1,
    shell:
        "CUDA_VISIBLE_DEVICES={BT_GPU} python {input.script}"


# Aggregation: the BERTopic baseline end to end (labels -> eval -> read-out).
rule bertopic:
    input:
        BT_BERTOPIC,
        BT_BERTOPIC_RAW,
        BT_EVAL_SUMMARY,
        BT_BERTOPIC_REPORT,
        BT_BERTOPIC_MD,


# Data-only aggregation: full-rank Doc2LoRA labels + vec2text/KeyLLM baselines +
# the auto-generated SI label tables. The main-text label tables
# (hierarchy_rows.tex, fields9 inline) are hand-composited from these (issue #15).
rule baseline_trees:
    input:
        BT_FULLRANK,
        BT_VEC2TEXT,
        BT_KEYLLM,
        BT_INCONTEXT,
        BT_HIER_ROWS,
        BT_EVAL_SUMMARY,
        BT_PACS_MAIN,
        BT_PACS_SI,
        # The length-dial figure left the paper; its CSV did not (Fig. cluster-labels and
        # the PACS label tables read it). Asking for the CSV, not the PDF, keeps the
        # 644k-paper gene matrix bt_length_dial reads out of `paper_assets`.
        BT_RADIUS_CSV,
