# PACS concept hierarchy (the node set every cluster-labelling table is built on).
#
# In the development repository this step was only reachable from a sub-Snakefile
# inside exps/2026-05-28-concept-analogy-aps (written for a Docker mount), so its
# two outputs looked like frozen artifacts. They are inputs to the manuscript's
# label chain (baseline_trees) and to the incoherent-cluster control, so the step
# is wired here instead:
#
#   ca_render_config -> exps/.../config.yaml     (derived from workflow/config.yaml,
#                                                 so paths have ONE source of truth)
#   ca_build_groups  -> results/paper_groups.parquet  one row per paper: PACS
#                       results/groups.parquet        one row per node: label + size
#                       results/tree.json             nested main -> ... -> specific
#
# build_groups.py reads the embedding file only for its `paper_ids` (which papers
# have a gene at all), so the rule points it at the gemma genes the workflow
# builds; the legacy `gemma_mean_pooled.npz` name it used has no producing rule.
from os.path import join as j

CA_DIR = "exps/2026-05-28-concept-analogy-aps"
CA_RESULTS = j(CA_DIR, "results")
CA_CONFIG = j(CA_DIR, "config.yaml")

CA_PAPER_GROUPS = j(CA_RESULTS, "paper_groups.parquet")
CA_GROUPS = j(CA_RESULTS, "groups.parquet")
CA_TREE = j(CA_RESULTS, "tree.json")

CA_MIN_GROUP_SIZE = config.get("pacs_min_group_size", 30)
CA_MIN_TEXT_LENGTH = config.get("pacs_min_text_length", 300)


rule ca_render_config:
    input:
        # not read by the rule, but declaring it keeps the config in step with the workflow
        workflow_config="workflow/config.yaml",
    output:
        cfg=CA_CONFIG,
    params:
        emb=j(EMB_DIR, "gemma_norm_lora_emb.npz"),
        paper_text=j(APS_DIR, "paper_text.parquet"),
        paper_table=config["aps_paper_table"],
        category_table=config.get("aps_category_table", ""),
        paper_category_table=config.get("aps_paper_category_table", ""),
        min_group_size=CA_MIN_GROUP_SIZE,
        min_text_length=CA_MIN_TEXT_LENGTH,
    run:
        import textwrap
        assert params.category_table and params.paper_category_table, (
            "set aps_category_table and aps_paper_category_table in workflow/config.yaml"
        )
        with open(output.cfg, "w") as fh:
            fh.write(textwrap.dedent(f"""\
                # GENERATED by workflow/rules/pacs_groups.smk from workflow/config.yaml.
                # Do not edit by hand -- edit workflow/config.yaml and re-run the rule.
                mean_pooled_embeddings: "{params.emb}"
                paper_text: "{params.paper_text}"
                paper_table: "{params.paper_table}"
                category_table: "{params.category_table}"
                paper_category_table: "{params.paper_category_table}"
                results_dir: "results"
                min_group_size: {params.min_group_size}
                min_text_length: {params.min_text_length}
                """))


rule ca_build_groups:
    input:
        cfg=CA_CONFIG,
        script=j(CA_DIR, "scripts", "build_groups.py"),
        emb=j(EMB_DIR, "gemma_norm_lora_emb.npz"),
        paper_text=j(APS_DIR, "paper_text.parquet"),
        paper_table=config["aps_paper_table"],
    output:
        paper_groups=CA_PAPER_GROUPS,
        groups=CA_GROUPS,
        tree=CA_TREE,
    resources:
        mem_gb=32,
    shell:
        "python {input.script}"


rule pacs_groups:
    input:
        CA_PAPER_GROUPS,
        CA_GROUPS,
        CA_TREE,
