"""Emit the recipe-fusion transcript (App. recipe-fusion) from
results/recipe_fusion.json produced by recipe_fusion.py.

The appendix quotes three verbatim blocks --- source A (Italian, cacio e pepe),
source B (Japanese, kake udon), and the decoded midpoint (alpha=0.5) --- plus the
"What cheese is used?" answer. This writes figs/recipe_fusion.tex: the three
snugshade+verbatim blocks the appendix \\input's, with each line wrapped to fit
the \\footnotesize verbatim column. Dual-mode:

  python fig_recipe_fusion.py <recipe_fusion.json> <out.tex>
"""
import json
import sys
import textwrap
from pathlib import Path

WIDTH = 78  # characters that fit a \footnotesize verbatim line in the column


def _wrap(text):
    """Re-flow only lines that exceed WIDTH (long model-decode steps); leave
    already-short source lines untouched. Wrapped continuations hang-indent so
    numbered/bulleted steps stay readable."""
    out = []
    for line in text.split("\n"):
        if len(line) <= WIDTH:
            out.append(line)
            continue
        lead = len(line) - len(line.lstrip(" "))
        # Numbered ("1. ") or bulleted ("- ") items hang-indent by 3 spaces.
        cont = " " * (lead + 3) if line.lstrip()[:2].rstrip(".").isdigit() or line.lstrip().startswith("- ") else " " * lead
        out.extend(textwrap.wrap(
            line, width=WIDTH, subsequent_indent=cont,
            break_long_words=False, break_on_hyphens=False,
        ) or [""])
    return "\n".join(out)


def _block(title, body):
    return "\n".join([
        f"\\textbf{{{title}}}",
        "",
        r"\begin{snugshade}",
        r"{\footnotesize\begin{verbatim}",
        _wrap(body.strip("\n")),
        r"\end{verbatim}}",
        r"\end{snugshade}",
        "",
    ])


def build(data):
    dec = data["decodes"]
    lines = [
        "% Auto-generated by workflow/plot/fig_recipe_fusion.py -- do not edit by hand.",
        "% The cheese-QA answer the appendix quotes inline:",
        f"% {dec.get('italian_cheese_qa', '').strip()}",
        "",
        _block(r"Source document $A$ (Italian).", data["doc_italian"]),
        _block(r"Source document $B$ (Japanese).", data["doc_japanese"]),
        _block(r"Decoded midpoint, $\alpha=0.5$.", dec["alpha_0.50"]),
    ]
    return "\n".join(lines)


if "snakemake" in sys.modules:
    in_json = snakemake.input["json"]
    out_tex = snakemake.output["table"]
elif len(sys.argv) > 2:
    in_json, out_tex = sys.argv[1], sys.argv[2]
else:
    in_json = "exps/2026-06-11-recipe-fusion/results/recipe_fusion.json"
    out_tex = "figs/recipe_fusion.tex"

Path(out_tex).write_text(build(json.load(open(in_json))))
print(f"wrote {out_tex}")
