"""Generate the full-featured S2AND table (tab:s2and-full) from the per-dataset
full_{ds}_qwen.csv files produced by s2and.smk:s2and_full.

Each CSV has rows metadata_only / specter / gene / gene_kron with columns
features, B3_P, B3_R, B3_F1, delta_vs_metadata. The table reports, per dataset:
metadata-only B3 F1, delta SPECTER (specter row), delta doc2lora (gene_kron row,
the adapted bijective-transform feature; bold).

Writes figs/s2and_full.tex -- the inner tabular that paper/iclr2026/main.tex
\\input's inside its table environment. Dual-mode:

  python tab_s2and_full.py <s2and_dir> <out.tex>
"""
import csv
import sys
from pathlib import Path

# Single encoder across the whole S2AND benchmark (matches tab:similarity).
ENC = "qwen"
# (csv dataset key, display label) in paper row order.
DATASETS = [
    ("zbmath", "zbMATH"),
    ("qian", "QIAN"),
    ("arnetminer", "ArnetMiner"),
    ("pubmed", "PubMed"),
    ("kisti", "KISTI"),
]


def _f3(x):
    """0.933 -> .933 ; -0.0 -> .000 (3 decimals, leading zero stripped)."""
    s = f"{float(x):.3f}"
    return s.replace("0.", ".", 1) if s.startswith(("0.", "-0.")) else s


def _delta(x):
    """0.006 -> +.006 ; -0.001 -> -.001 (signed, 3 decimals, leading dot)."""
    v = float(x)
    body = f"{abs(v):.3f}".replace("0.", ".", 1)
    return f"+{body}" if v >= 0 else f"-{body}"


def _rows(csv_path):
    by_feat = {}
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            by_feat[r["features"]] = r
    return by_feat


def build(s2and_dir):
    s2and_dir = Path(s2and_dir)
    lines = [
        "% Auto-generated by workflow/plot/tab_s2and_full.py -- do not edit by hand.",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Dataset & metadata-only B\textsuperscript{3} & $\Delta$\texttt{SPECTER} & $\Delta$\doctolora \\",
        r"\midrule",
    ]
    for key, label in DATASETS:
        feats = _rows(s2and_dir / f"full_{key}_{ENC}.csv")
        meta = _f3(feats["metadata_only"]["B3_F1"])
        d_spec = _delta(feats["specter"]["delta_vs_metadata"])
        d_d2l = _delta(feats["gene_kron"]["delta_vs_metadata"])
        lines.append(
            f"{label:<10} & {meta} & ${d_spec}$ & $\\mathbf{{{d_d2l}}}$ \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


if "snakemake" in sys.modules:
    s2and_dir = snakemake.params["s2and_dir"]
    out_tex = snakemake.output["table"]
elif len(sys.argv) > 2:
    s2and_dir, out_tex = sys.argv[1], sys.argv[2]
else:
    s2and_dir, out_tex = "exps/2026-06-09-s2and", "figs/s2and_full.tex"

Path(out_tex).write_text(build(s2and_dir))
print(f"wrote {out_tex}")
