"""[CPU] Collaboration AUC per anchor window, from the manuscript's own pools (#145).

Table 1 reports one AUC over the candidate pairs of every anchor window pooled together. That
hides whether a method leads in every window or only on average, so this table reports each window
separately, with the pooled column beside it for reference. Same pools, same methods, same units as
Table 1 -- only the grouping differs.

Out: figs/collab_per_window.tex
"""
import os

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

POOLS = snakemake.params.pools                        # noqa: F821
FIELDS = list(snakemake.params.fields)                # noqa: F821
ENC = snakemake.params.enc                            # noqa: F821
OUT = snakemake.output.table                          # noqa: F821

NICE = [(ENC, "\\doctolora (raw)"), (f"{ENC}_genkron", "\\quad $+g_\\theta$"),
        ("specter2", "\\texttt{SPECTER2}"), ("sbert", "\\texttt{SBERT}"),
        ("instructor", "\\texttt{Instructor}"),
        ("embeddinggemma", "\\texttt{EmbeddingGemma}"), ("gte", "\\texttt{GTE}")]
SHORT = {"aps": "Physics", "economics": "Economics", "psychology": "Psychology"}


def nz(v):
    """Drop the leading zero, matching \\tabref{similarity}."""
    if not np.isfinite(v):
        return "---"
    s = f"{v:.3f}"
    return s.replace("0.", ".", 1) if abs(v) < 1 else s


def auc(y, s):
    m = np.isfinite(s)
    return roc_auc_score(y[m], s[m]) if len(np.unique(y[m])) > 1 else np.nan


cells, windows = {}, {}
for field in FIELDS:
    d = pd.read_parquet(f"{POOLS}/collab_{field}_{ENC}.parquet")
    windows[field] = sorted(int(w) for w in d.window.unique())
    for col, _ in NICE:
        if col not in d.columns:
            continue
        y = d.y.values.astype(float)
        s = d[col].values.astype(float)
        for t in windows[field]:
            m = d.window.values == t
            cells[(field, t, col)] = auc(y[m], s[m])
        cells[(field, "pooled", col)] = auc(y, s)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
groups = [(f, windows[f] + ["pooled"]) for f in FIELDS]
ncol = sum(len(ws) for _, ws in groups)
with open(OUT, "w") as fh:
    fh.write("% auto-generated by workflow/scripts/groupc/collab_per_window.py (#145) -- do not edit\n")
    fh.write("\\begin{tabular}{l" + "r" * ncol + "}\n\\toprule\n")
    fh.write("method" + "".join(f" & \\multicolumn{{{len(ws)}}}{{c}}{{{SHORT.get(f, f)}}}"
                                for f, ws in groups) + " \\\\\n")
    fh.write("".join(f"\\cmidrule(lr){{{2 + sum(len(w) for _, w in groups[:i])}-"
                     f"{1 + sum(len(w) for _, w in groups[:i + 1])}}}"
                     for i in range(len(groups))) + "\n")
    fh.write("".join(" & " + (str(w) if w != "pooled" else "pooled")
                     for _, ws in groups for w in ws) + " \\\\\n\\midrule\n")
    for col, label in NICE:
        fh.write(label + " & "
                 + " & ".join(nz(cells.get((f, w, col), np.nan)) for f, ws in groups for w in ws)
                 + " \\\\\n")
    fh.write("\\bottomrule\n\\end{tabular}\n")

print(pd.DataFrame([{"field": f, "window": w, **{lab: round(cells.get((f, w, c), np.nan), 4)
                                                 for c, lab in [(x[0], x[0]) for x in NICE]}}
                    for f, ws in groups for w in ws]).to_string(index=False))
print(f"[saved] {OUT}")
