"""[CPU] Assemble the #71 efficiency table: cost per encoder + storage/PQ cost per representation.

Out: eff_summary.csv, figs/efficiency.tex (two blocks: encoding cost, index cost)
"""
import json
import os

import pandas as pd

rows = []
for p in snakemake.input.throughput:                # noqa: F821
    rows.append(json.load(open(p)))
T = pd.DataFrame(rows)
IDX = json.load(open(snakemake.input.index))        # noqa: F821

NICE = {"d2l-qwen": "Doc2LoRA (Qwen3-4B)", "d2l-mistral": "Doc2LoRA (Mistral-7B)",
        "d2l-gemma": "Doc2LoRA (Gemma-2-2B)", "icae": "ICAE (Mistral-7B)",
        "sbert": "SBERT all-mpnet", "specter2": "SPECTER2"}
ORDER = ["sbert", "specter2", "icae", "d2l-gemma", "d2l-qwen", "d2l-mistral"]
T["order"] = T.method.map({m: i for i, m in enumerate(ORDER)}).fillna(99)
T = T.sort_values("order")
os.makedirs(os.path.dirname(snakemake.output.csv), exist_ok=True)    # noqa: F821
T.to_csv(snakemake.output.csv, index=False)                          # noqa: F821
print(T.to_string(index=False), flush=True)

corpus = IDX["corpus_size"]
with open(snakemake.output.table, "w") as fh:                        # noqa: F821
    fh.write("% auto-generated by workflow/scripts/groupc/eff_report.py (issue #71) -- do not edit\n")
    fh.write("\\begin{tabular}{lrrrr}\n\\toprule\n")
    fh.write("encoder & parameters & docs/s & peak VRAM (GB) & embedding dims \\\\\n\\midrule\n")
    for _, r in T.iterrows():
        fh.write(f"{NICE.get(r.method, r.method)} & {int(r.params) / 1e6:,.0f}M & "
                 f"{r.docs_per_sec:.1f} & {r.peak_vram_gb:.1f} & {int(r.dim_pooled):,} \\\\\n"
                 .replace(",", "{,}"))
    fh.write("\\bottomrule\n\\end{tabular}\n")

with open(snakemake.output.index_table, "w") as fh:                  # noqa: F821
    fh.write("% auto-generated by workflow/scripts/groupc/eff_report.py (issue #71) -- do not edit\n")
    fh.write("\\begin{tabular}{lrrrr}\n\\toprule\n")
    fh.write("representation & dims & bytes/paper & index at "
             f"{corpus / 1e6:.1f}M papers & PQ recall@10 (bytes/paper) \\\\\n\\midrule\n")
    for label, rec in IDX["reps"].items():
        pq = sorted(rec.get("pq", []), key=lambda x: -x["m_bytes"])
        pqs = "; ".join(f"{q['recall_at_10']:.2f} ({q['m_bytes']} B)" for q in pq) or "---"
        fh.write(f"{label} & {rec['dim']:,} & {rec['bytes_per_paper_fp16']:,} B & "
                 f"{rec['index_gb_fp16']:.1f} GB & {pqs} \\\\\n".replace(",", "{,}"))
    fh.write("\\bottomrule\n\\end{tabular}\n")
print(f"[eff-report] wrote {snakemake.output.table}, {snakemake.output.index_table}",   # noqa: F821
      flush=True)
