"""[CPU] Appendix table of the RAW scores behind fig:symmetric-gain (#145).

The figure shows only the gain from g_theta, so the level each space starts from (ICAE lowest)
needs its own short table: one row per space, one column per task, each cell the raw score averaged
over that task's benchmarks (3 fields, or the 5 S2AND datasets).

Dual-mode: Snakemake or CLI.
  python workflow/scripts/groupc/gcb_raw_table.py <gcb_summary.csv> <gcb_s2and_summary.csv> <out.tex>
"""
import os
import sys

import pandas as pd

FIELDS = ["aps", "economics", "psychology"]
S2AND = ["zbmath", "qian", "arnetminer", "pubmed", "kisti"]
# (row label, raw key on the field benchmarks, raw key on S2AND)
SPACES = [("\\doctolora (Qwen3-4B)", "gene", "gene"),
          ("\\texttt{ICAE} (Mistral-7B)", "icae", "icae"),
          ("\\texttt{SBERT}", "sbert", "sbert"),
          ("\\texttt{EmbeddingGemma}", "embeddinggemma", "embeddinggemma"),
          ("\\texttt{Instructor}", "instructor", "instructor"),
          ("\\texttt{SPECTER2} / \\texttt{SPECTER}", "specter2", "specter"),
          ("\\texttt{GTE}", "gte", "gte")]
TASKS = [("collab", "Collab.\\ (AUC)"), ("np", "Next paper (AUC)"),
         ("topic", "Topic (F1)"), ("name_disambig", "Disamb.\\ (B\\textsuperscript{3} F1)")]


def build(field_csv, s2and_csv, out):
    A = pd.concat([pd.read_csv(field_csv), pd.read_csv(s2and_csv)], ignore_index=True)
    look = {(r.field, r.task, r.method): r.value for r in A.itertuples()}
    lines = []
    for label, fkey, skey in SPACES:
        cells = []
        for task, _ in TASKS:
            if task == "name_disambig":
                vals = [look[(ds, task, skey)] for ds in S2AND]
            else:
                vals = [look[(f, task, fkey)] for f in FIELDS]
            cells.append(sum(vals) / len(vals))
        lines.append((label, cells))
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as fh:
        fh.write("% auto-generated by workflow/scripts/groupc/gcb_raw_table.py (#145) -- do not edit\n")
        fh.write("\\begin{tabular}{l" + "r" * len(TASKS) + "}\n\\toprule\n")
        fh.write("space & " + " & ".join(h for _, h in TASKS) + " \\\\\n\\midrule\n")
        for label, cells in lines:
            fh.write(label + " & " + " & ".join(f"{v:.3f}".lstrip("0") for v in cells) + " \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    for label, cells in lines:
        print(label, [round(v, 3) for v in cells])
    print(f"[saved] {out}")


if __name__ == "__main__" and "snakemake" not in globals():
    build(*sys.argv[1:4])
else:
    build(snakemake.input.fields, snakemake.input.s2and, snakemake.output.table)  # noqa: F821
