"""[CPU] Appendix summary of the symmetric-supervision control (#145).

One row per embedding space: what the SAME citation transform does to it, measured as a paired
difference (adapted minus raw on identical resampled units, gcb_headtohead.py), plus how many of
the 14 tests move in each direction with an interval that excludes zero.

Out: figs/symmetric_adapter_summary.tex
"""
import os

import pandas as pd

IN = list(snakemake.input.pairs)                     # noqa: F821
OUT = snakemake.output.table                         # noqa: F821

NICE = {"gene": "\\doctolora (Qwen3-4B)", "sbert": "\\texttt{SBERT}",
        "specter2": "\\texttt{SPECTER2} / \\texttt{SPECTER}", "instructor": "\\texttt{Instructor}",
        "embeddinggemma": "\\texttt{EmbeddingGemma}", "gte": "\\texttt{GTE}",
        "icae": "\\texttt{ICAE}"}

def _nz(v, dec=3, sign=False):
    """Format a quantity bounded by 1 without its leading zero, matching Table 1."""
    s = f"{v:+.{dec}f}" if sign else f"{v:.{dec}f}"
    return s.replace("0.", ".", 1) if abs(v) < 1 else s


rows = []
for f in IN:
    d = pd.read_csv(f)
    space = d.b.iloc[0]
    rows.append({"space": space, "mean": d["diff"].mean(),
                 "up": int((d.diff_lo > 0).sum()), "down": int((d.diff_hi < 0).sum()),
                 "lo": d["diff"].min(), "hi": d["diff"].max(), "n": len(d)})
S = pd.DataFrame(rows).sort_values("mean", ascending=False)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("% auto-generated by workflow/scripts/groupc/gcb_headtohead_table.py (#145) -- do not edit\n")
    fh.write("\\begin{tabular}{lrrrr}\n\\toprule\n")
    fh.write("space & mean $\\Delta$ & range & better & worse \\\\\n\\midrule\n")
    for _, r in S.iterrows():
        fh.write(f"{NICE.get(r.space, r.space)} & {_nz(r['mean'], sign=True)} & "
                 f"[{_nz(r.lo, sign=True)}, {_nz(r.hi, sign=True)}] & "
                 f"{r.up}/{r.n} & {r.down}/{r.n} \\\\\n")
    fh.write("\\bottomrule\n\\end{tabular}\n")
print(S.round(4).to_string(index=False))
print(f"[saved] {OUT}")
