"""[GPU-light] Score the #101 incoherent-cluster control.

Two instruments, one deterministic and one judged, both blind to the arm:

  (1) label-member agreement (no LLM): SBERT cosine between the decoded label and the centroid of
      its own members' abstracts, plus the margin against every other cluster's member centroid and
      the rank of the own-cluster centroid.  If a label reports the cluster's shared content, its own
      members should be its nearest cluster; if it only reports the centroid's norm, they should not.

  (2) blinded judge panel (the roster already used for the cluster-label metrics): given 12 sampled
      member titles and a candidate label, does the set belong to the named field, and is the label
      specific, broad, or a generic non-answer?  The judge never sees which arm a row came from.

Out: data/groupc/incoherent/incoh_scores.json, figs/incoherent_control.tex, .../incoherent_control.pdf
"""
import json
import os
import random
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, "workflow/plot")
sys.path.insert(0, "data/labels")

NICE = {"real": "PACS node (real)", "control_native": "cross-chapter control",
        "control_matched": "cross-chapter, norm-matched"}


def pct(x):
    """0.733 -> '73.3', 0.73 -> '73'. Tenths matter at n=30 (one node is 3.3%)."""
    return f"{100 * x:.1f}".removesuffix(".0")


def write_table(summary, judge_summary, path):
    """figs/incoherent_control.tex: does the blinded panel accept the label, per arm.

    altitude_specific is deliberately not a column: it grades how concrete a label
    sounds, not whether it is right, so the controls outscore the real nodes on it and
    the table would read as if it contradicted the appendix. It stays in the JSON.

    A pure function of what incoh_scores.json already holds, so a column change never
    costs a judge call -- see the CLI entry point below.
    """
    with open(path, "w") as fh:
        fh.write("% auto-generated by workflow/scripts/groupc/incoh_score.py (issue #101) -- do not edit\n")
        if not judge_summary:
            fh.write("% no judge panel in this run: nothing to report\n")
            return
        fh.write("\\begin{tabular}{lrrr}\n\\toprule\n")
        fh.write("cluster set & $n$ & belongs=yes & rejected\\\\\n\\midrule\n")
        for cond in ("real", "control_native", "control_matched"):
            if cond not in summary or cond not in judge_summary:
                continue
            jj = judge_summary[cond]
            fh.write(f"{NICE[cond]} & {summary[cond]['n']} & {pct(jj['belongs_yes'])}\\% & "
                     f"{pct(jj['belongs_no'])}\\% \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")


if "snakemake" not in globals():
    # CLI: rebuild only the LaTeX table from an existing incoh_scores.json. No GPU, no SBERT
    # and no judge calls -- the table reads the summary the rule already wrote.
    #   python workflow/scripts/groupc/incoh_score.py <incoh_scores.json> <out.tex>
    _doc = json.load(open(sys.argv[1]))["summary"]
    write_table(_doc, {c: s["judge"] for c, s in _doc.items() if "judge" in s}, sys.argv[2])
    print(f"wrote {sys.argv[2]}", flush=True)
    sys.exit(0)


LABELS = json.load(open(snakemake.input.labels))            # noqa: F821
CLUSTERS = json.load(open(snakemake.input.clusters))        # noqa: F821
NODES_EVAL = json.load(open(snakemake.params.nodes_eval))   # noqa: F821  ground-truth PACS labels
N_TITLES = int(snakemake.params.n_titles)                   # noqa: F821
N_MEMBERS_SBERT = int(snakemake.params.n_members_sbert)     # noqa: F821
SEED = int(snakemake.params.seed)                           # noqa: F821
USE_JUDGES = bool(snakemake.params.use_judges)              # noqa: F821

gt = {str(n["code"]): n.get("gt_label", "") for n in NODES_EVAL}
members = {c["node"]: c["members"] for c in CLUSTERS["real"]}
members.update({c["cid"]: c["members"] for c in CLUSTERS["control"]})

rows = []
for cond in ("real", "control_native", "control_matched"):
    for cid, rec in LABELS[cond].items():
        rows.append({"cond": cond, "cluster": cid, "label": rec["label"], "norm": rec["norm"],
                     "match_node": rec.get("match_node", cid),
                     "gt_label": gt.get(rec.get("match_node", cid), "")})
R = pd.DataFrame(rows)
print(f"[incoh-score] {len(R)} rows: " + ", ".join(f"{k}={v}" for k, v in R.cond.value_counts().items()),
      flush=True)

# ── (1) deterministic label-member agreement via SBERT ─────────────────────────────────
txt = pd.read_parquet(snakemake.input.paper_text)            # noqa: F821
idc = "aps_paper_id" if "aps_paper_id" in txt.columns else "paper_id"
id2title = dict(zip(txt[idc].astype(int), txt["title"].astype(str)))
id2text = dict(zip(txt[idc].astype(int), txt["text"].astype(str)))

from sentence_transformers import SentenceTransformer  # noqa: E402

sb = SentenceTransformer(snakemake.params.sbert_model)       # noqa: F821
rng = np.random.default_rng(SEED)

cl_ids = list(dict.fromkeys(R.cluster.tolist()))
cent = {}
for cid in cl_ids:
    mem = members[cid]
    sel = mem if len(mem) <= N_MEMBERS_SBERT else rng.choice(mem, N_MEMBERS_SBERT, replace=False)
    docs = [id2text[int(p)] for p in sel if int(p) in id2text]
    E = sb.encode(docs, batch_size=128, convert_to_numpy=True, normalize_embeddings=True,
                  show_progress_bar=False)
    v = E.mean(0)
    cent[cid] = v / (np.linalg.norm(v) + 1e-9)
C = np.stack([cent[c] for c in cl_ids])
cidx = {c: i for i, c in enumerate(cl_ids)}

lab_vecs = sb.encode(R.label.tolist(), batch_size=64, convert_to_numpy=True,
                     normalize_embeddings=True, show_progress_bar=False)
S = lab_vecs @ C.T                                   # [rows, clusters]
own = np.array([S[i, cidx[c]] for i, c in enumerate(R.cluster)])
others = S.copy()
for i, c in enumerate(R.cluster):
    others[i, cidx[c]] = -np.inf
R["cos_own"] = own
R["cos_best_other"] = others.max(1)
R["margin"] = R.cos_own - R.cos_best_other
R["rank_own"] = [(S[i] > S[i, cidx[c]]).sum() + 1 for i, c in enumerate(R.cluster)]
R["hit_at_1"] = (R.rank_own == 1).astype(int)

# ── (2) blinded judge panel ────────────────────────────────────────────────────────────
JUDGE_SYS = (
    "You are grading whether a short label correctly names the research area of a set of physics "
    "papers. Answer ONLY with a JSON object: "
    '{"belongs": "yes|partial|no", "altitude": "specific|broad|generic", "reason": "<12 words"}. '
    '"belongs": does the label name a research area that the listed papers actually share? '
    '"altitude": is the label a specific research topic, a broad subfield, or a generic '
    'non-answer such as "science" or "physics research"?'
)

judge_summary = {}
if USE_JUDGES:
    # JUDGES_V2, not the legacy roster: figs/incoherent_control.tex as committed was
    # produced by the current panel, and a generator that disagrees with the table it
    # writes is how App. E.1 came to sit on a stale panel in the first place.
    from label_eval_judges import JUDGES_V2 as JUDGES, judge_json, run_jobs  # noqa: E402

    rnd = random.Random(SEED)
    jobs = []
    for i, r in R.iterrows():
        mem = members[r.cluster]
        sel = mem if len(mem) <= N_TITLES else rnd.sample(list(mem), N_TITLES)
        titles = [id2title.get(int(p), "") for p in sel]
        titles = [t for t in titles if t.strip()][:N_TITLES]
        user = ("Candidate label: " + r.label + "\n\nPapers:\n" +
                "\n".join(f"- {t}" for t in titles))
        for jname, slug in JUDGES.items():
            jobs.append({"row": int(i), "judge": jname, "slug": slug, "user": user})
    print(f"[incoh-score] {len(jobs)} judge calls ({len(JUDGES)} judges x {len(R)} rows)", flush=True)
    res = run_jobs(jobs, lambda it: judge_json(it["slug"], JUDGE_SYS, it["user"]), max_workers=8)

    per_row = {i: {"belongs": [], "altitude": []} for i in R.index}
    for it, out in zip(jobs, res):
        if not isinstance(out, dict) or "_error" in out:
            continue
        b = str(out.get("belongs", "")).lower().strip()
        al = str(out.get("altitude", "")).lower().strip()
        if b in ("yes", "partial", "no"):
            per_row[it["row"]]["belongs"].append(b)
        if al in ("specific", "broad", "generic"):
            per_row[it["row"]]["altitude"].append(al)

    def majority(xs, order):
        if not xs:
            return ""
        return max(order, key=lambda o: (xs.count(o), -order.index(o)))

    R["belongs"] = [majority(per_row[i]["belongs"], ["yes", "partial", "no"]) for i in R.index]
    R["altitude"] = [majority(per_row[i]["altitude"], ["specific", "broad", "generic"]) for i in R.index]
    R["belongs_yes_frac"] = [
        (per_row[i]["belongs"].count("yes") / len(per_row[i]["belongs"])) if per_row[i]["belongs"] else np.nan
        for i in R.index]
    R["n_judges"] = [len(per_row[i]["belongs"]) for i in R.index]
    judge_summary = {
        cond: {
            "belongs_yes": float((g.belongs == "yes").mean()),
            "belongs_partial": float((g.belongs == "partial").mean()),
            "belongs_no": float((g.belongs == "no").mean()),
            "belongs_yes_frac_mean": float(g.belongs_yes_frac.mean()),
            "altitude_specific": float((g.altitude == "specific").mean()),
            "altitude_broad": float((g.altitude == "broad").mean()),
            "altitude_generic": float((g.altitude == "generic").mean()),
        } for cond, g in R.groupby("cond")
    }

# ── summary ───────────────────────────────────────────────────────────────────────────
summary = {}
for cond, g in R.groupby("cond"):
    summary[cond] = {
        "n": int(len(g)),
        "cos_own_mean": float(g.cos_own.mean()), "cos_own_sd": float(g.cos_own.std(ddof=1)),
        "margin_mean": float(g.margin.mean()), "hit_at_1": float(g.hit_at_1.mean()),
        "norm_mean": float(g.norm.mean()),
    }
    if cond in judge_summary:
        summary[cond]["judge"] = judge_summary[cond]
os.makedirs(os.path.dirname(snakemake.output.scores), exist_ok=True)   # noqa: F821
with open(snakemake.output.scores, "w") as fh:                          # noqa: F821
    json.dump({"summary": summary, "rows": R.to_dict(orient="records")}, fh, indent=1)
R.to_parquet(snakemake.output.rows, index=False)                        # noqa: F821
print(json.dumps(summary, indent=1), flush=True)

# ── LaTeX table ────────────────────────────────────────────────────────────
# The table carries one question and nothing else (#159): does the blinded panel accept the
# label as naming a field the members share? The norm, the label--members cosine and the
# members-are-nearest share were three more instruments aimed at that same question, and the
# norm column in particular invited reading the control as a norm experiment. The dropped
# quantities are still in incoh_scores.json and in the figure.
write_table(summary, judge_summary, snakemake.output.table)              # noqa: F821

# ── figure: label-member agreement per arm (dots + medians, no bars) ──────────────────
import matplotlib.pyplot as plt              # noqa: E402
from _style import finalize, setup_style     # noqa: E402

setup_style(font_scale=1.1)
fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.6))
order = [c for c in ("real", "control_native", "control_matched") if c in set(R.cond)]
jit = np.random.default_rng(SEED)
for ax, col, lab in ((axes[0], "cos_own", "label vs own members (SBERT cos.)"),
                     (axes[1], "margin", "own minus best other cluster")):
    for x, cond in enumerate(order):
        v = R.loc[R.cond == cond, col].values
        ax.scatter(x + jit.normal(0, 0.06, len(v)), v, s=18, alpha=0.55)
        ax.hlines(np.median(v), x - 0.25, x + 0.25, color="k", lw=2, zorder=5)
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels(["real", "control", "control\n(norm-matched)"][:len(order)], fontsize=9)
    ax.set_ylabel(lab, fontsize=9)
    ax.axhline(0, color="0.7", lw=0.8, zorder=0)
finalize(fig, snakemake.output.fig)                                     # noqa: F821
print(f"[incoh-score] wrote {snakemake.output.scores}, {snakemake.output.table}, "   # noqa: F821
      f"{snakemake.output.fig}", flush=True)                                          # noqa: F821
