"""Tab. incoherent-control and its figure, drawn from the scored rows of the #101 control.

incoh_score.py does the expensive part (SBERT over member abstracts, the blinded judge
panel) and writes incoh_scores.json + incoh_rows.parquet. This script only reads those
two files, so the table and the figure rebuild on a CPU from the archived scores.

Dual mode: driven by Snakemake (rule incoh_report in workflow/rules/groupc_incoherent.smk) or

    python workflow/scripts/groupc/incoh_report.py <incoh_scores.json> <out.tex> \
        [--rows incoh_rows.parquet --fig out.pdf --seed 0]
"""
import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

NICE = {"real": "PACS node (real)", "control_native": "cross-chapter control",
        "control_matched": "cross-chapter, norm-matched"}


def pct(x):
    """0.733 -> '73.3', 0.73 -> '73'. Tenths matter at n=30 (one node is 3.3%)."""
    return f"{100 * x:.1f}".removesuffix(".0")


def write_table(summary, judge_summary, path):
    """figs/incoherent_control.tex: does the blinded panel accept the label, per arm.

    altitude_specific is deliberately not a column: it grades how concrete a label
    sounds, not whether it is right, so the controls outscore the real nodes on it and
    the table would read as if it contradicted the appendix. It stays in the JSON.

    A pure function of what incoh_scores.json already holds, so a column change never
    costs a judge call -- see the CLI entry point below.
    """
    with open(path, "w") as fh:
        fh.write("% auto-generated by workflow/scripts/groupc/incoh_score.py (issue #101) -- do not edit\n")
        if not judge_summary:
            fh.write("% no judge panel in this run: nothing to report\n")
            return
        fh.write("\\begin{tabular}{lrrr}\n\\toprule\n")
        fh.write("cluster set & $n$ & belongs=yes & rejected\\\\\n\\midrule\n")
        for cond in ("real", "control_native", "control_matched"):
            if cond not in summary or cond not in judge_summary:
                continue
            jj = judge_summary[cond]
            fh.write(f"{NICE[cond]} & {summary[cond]['n']} & {pct(jj['belongs_yes'])}\\% & "
                     f"{pct(jj['belongs_no'])}\\% \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")


def write_figure(R, seed, path):
    """Label-member agreement per arm (dots + medians, no bars)."""
    sys.path.insert(0, "workflow/plot")
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from _style import finalize, setup_style

    setup_style(font_scale=1.1)
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.6))
    order = [c for c in ("real", "control_native", "control_matched") if c in set(R.cond)]
    jit = np.random.default_rng(seed)
    for ax, col, lab in ((axes[0], "cos_own", "label vs own members (SBERT cos.)"),
                         (axes[1], "margin", "own minus best other cluster")):
        for x, cond in enumerate(order):
            v = R.loc[R.cond == cond, col].values
            ax.scatter(x + jit.normal(0, 0.06, len(v)), v, s=18, alpha=0.55)
            ax.hlines(np.median(v), x - 0.25, x + 0.25, color="k", lw=2, zorder=5)
        ax.set_xticks(range(len(order)))
        ax.set_xticklabels(["real", "control", "control\n(norm-matched)"][:len(order)], fontsize=9)
        ax.set_ylabel(lab, fontsize=9)
        ax.axhline(0, color="0.7", lw=0.8, zorder=0)
    finalize(fig, path)


def main(scores, table, rows=None, fig=None, seed=0):
    summary = json.load(open(scores))["summary"]
    # The table carries one question and nothing else (#159): does the blinded panel accept
    # the label as naming a field the members share? The norm, the label--members cosine and
    # the members-are-nearest share are still in incoh_scores.json and in the figure.
    os.makedirs(os.path.dirname(os.path.abspath(table)), exist_ok=True)
    write_table(summary, {c: s["judge"] for c, s in summary.items() if "judge" in s}, table)
    print(f"[incoh-report] wrote {table}", flush=True)
    if rows and fig:
        write_figure(pd.read_parquet(rows), seed, fig)
        print(f"[incoh-report] wrote {fig}", flush=True)


if "snakemake" in globals():
    main(snakemake.input.scores, snakemake.output.table, snakemake.input.rows,   # noqa: F821
         snakemake.output.fig, int(snakemake.params.seed))                       # noqa: F821
elif __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("scores")
    ap.add_argument("table")
    ap.add_argument("--rows")
    ap.add_argument("--fig")
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    main(a.scores, a.table, a.rows, a.fig, a.seed)
