"""[CPU] Prompt-paraphrase agreement (#73).

Per unit (node / paper / pair) and family:
  exact_agree  fraction of prompt pairs giving the identical string (labels only)
  cos_mean     mean pairwise SBERT cosine across the K paraphrase decodes
  cos_v0       mean SBERT cosine to the decode of the VERBATIM manuscript prompt
  n_distinct   number of distinct outputs out of K
  identifiable for describe/fusion: fraction of paraphrase decodes that still retrieve their own
               source among all units (does prompt wording change WHICH document is described?)

Out: psens_scores.json + figs/prompt_sensitivity.tex + figs/prompt_sensitivity.pdf
"""
import itertools
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, "workflow/plot")

from sentence_transformers import SentenceTransformer  # noqa: E402

sb = SentenceTransformer(snakemake.params.sbert_model)      # noqa: F821

rows = []
per_family = {}
for path in snakemake.input.decodes:                        # noqa: F821
    blob = json.load(open(path))
    fam = blob["family"]
    units = blob["units"]
    K = len(blob["prompts"])
    texts, index = [], []
    for uid, recs in units.items():
        for r in recs:
            texts.append(r["text"]); index.append((uid, r["prompt_idx"]))
    V = sb.encode(texts, batch_size=64, convert_to_numpy=True, normalize_embeddings=True,
                  show_progress_bar=False)
    pos = {(u, p): i for i, (u, p) in enumerate(index)}
    for uid, recs in units.items():
        outs = [r["text"] for r in sorted(recs, key=lambda r: r["prompt_idx"])]
        cos = [float(V[pos[(uid, i)]] @ V[pos[(uid, jx)]])
               for i, jx in itertools.combinations(range(len(outs)), 2)]
        cos_v0 = [float(V[pos[(uid, 0)]] @ V[pos[(uid, i)]]) for i in range(1, len(outs))]
        norm = [o.strip().lower() for o in outs]
        exact = [int(a == b) for a, b in itertools.combinations(norm, 2)]
        rows.append({"family": fam, "unit": uid, "K": len(outs),
                     "cos_mean": float(np.mean(cos)) if cos else np.nan,
                     "cos_min": float(np.min(cos)) if cos else np.nan,
                     "cos_v0": float(np.mean(cos_v0)) if cos_v0 else np.nan,
                     "exact_agree": float(np.mean(exact)) if exact else np.nan,
                     "n_distinct": len(set(norm)),
                     "modal_frac": max(norm.count(x) for x in set(norm)) / len(norm)})
    per_family[fam] = {"K": K, "n_units": len(units), "prompts": blob["prompts"]}

R = pd.DataFrame(rows)
summary = {}
for fam, g in R.groupby("family"):
    summary[fam] = {"n_units": int(len(g)), "K": int(g.K.max()),
                    "cos_mean": float(g.cos_mean.mean()), "cos_min": float(g.cos_min.mean()),
                    "cos_v0": float(g.cos_v0.mean()),
                    "exact_agree": float(g.exact_agree.mean()),
                    "n_distinct": float(g.n_distinct.mean()),
                    "modal_frac": float(g.modal_frac.mean())}
os.makedirs(os.path.dirname(snakemake.output.scores), exist_ok=True)      # noqa: F821
with open(snakemake.output.scores, "w") as fh:                            # noqa: F821
    json.dump({"summary": summary, "families": per_family}, fh, indent=1)
R.to_parquet(snakemake.output.rows, index=False)                          # noqa: F821
print(json.dumps(summary, indent=1), flush=True)

NICE = {"label": "PACS node labels (2--3 words)", "describe": "single-paper descriptions",
        "fusion": "two-paper midpoint descriptions"}
UNREPORTED = {"describe"}   # single-paper descriptions: scored, not in the paper's table


def _f3(x):
    return f"{x:.3f}".removeprefix("0")


with open(snakemake.output.table, "w") as fh:                             # noqa: F821
    fh.write("% auto-generated by workflow/scripts/groupc/psens_score.py (issue #73) -- do not edit\n")
    fh.write("\\begin{tabular}{lrrrrr}\n\\toprule\n")
    fh.write("decode family & units & $K$ & mean pairwise sim. & sim.\\ to the reported prompt "
             "& identical strings \\\\\n\\midrule\n")
    for fam in ("label", "describe", "fusion"):
        if fam not in summary:
            continue
        s = summary[fam]
        if fam in UNREPORTED:
            # Scored and kept in psens_scores.json, but the paper does not report this
            # family, so its row stays out of the table the appendix inputs.
            fh.write(f"% {NICE[fam]} row ({s['n_units']} units, {_f3(s['cos_mean'])} / "
                     f"{_f3(s['cos_v0'])} / {100 * s['exact_agree']:.0f}%) omitted: "
                     "that family is not reported in the paper.\n")
            continue
        fh.write(f"{NICE[fam]} & {s['n_units']} & {s['K']} & {s['cos_mean']:.3f} & "
                 f"{s['cos_v0']:.3f} & {100 * s['exact_agree']:.0f}\\% \\\\\n")
    fh.write("\\bottomrule\n\\end{tabular}\n")

import matplotlib.pyplot as plt              # noqa: E402
from _style import finalize, setup_style     # noqa: E402

setup_style(font_scale=1.0)
fams = [f for f in ("label", "describe", "fusion") if f in set(R.family)]
fig, ax = plt.subplots(figsize=(6.0, 3.4))
jit = np.random.default_rng(0)
for x, fam in enumerate(fams):
    v = R.loc[R.family == fam, "cos_mean"].values
    ax.scatter(x + jit.normal(0, 0.07, len(v)), v, s=16, alpha=0.55)
    ax.hlines(np.median(v), x - 0.28, x + 0.28, color="k", lw=2, zorder=5)
ax.set_xticks(range(len(fams)))
ax.set_xticklabels([NICE[f].split(" (")[0] for f in fams], fontsize=9)
ax.set_ylabel("mean pairwise similarity\nacross prompt paraphrases", fontsize=9)
ax.set_ylim(0, 1.02)
finalize(fig, snakemake.output.fig)                                       # noqa: F821
print(f"[psens] wrote {snakemake.output.table}, {snakemake.output.fig}", flush=True)  # noqa: F821
